// AUTO-GENERATED from db/drinks/*.json by scripts/build-drinks.ts
// Do not edit by hand. Regenerate with: npm run db:build

export interface DrinkCatalogEntry {
  name: string;
  category: string | null;
  defaultMilk: string | null;
  defaultIced: boolean;
  hasHot: boolean;
  hasIced: boolean;
  recipeIngredients: readonly string[];
}

export const drinkCatalog: readonly DrinkCatalogEntry[] = [
  {
    name: "Americano",
    category: "espresso",
    defaultMilk: null,
    defaultIced: false,
    hasHot: true,
    hasIced: true,
    recipeIngredients: ["espresso"],
  },
  {
    name: "Brown Sugar Oatmilk Shaken Espresso",
    category: "espresso",
    defaultMilk: "Oatmilk",
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["cinnamon powder","classic syrup","espresso"],
  },
  {
    name: "Caramel Macchiato",
    category: "espresso",
    defaultMilk: "2%",
    defaultIced: false,
    hasHot: true,
    hasIced: true,
    recipeIngredients: ["caramel drizzle","espresso","vanilla syrup"],
  },
  {
    name: "Caramel Ribbon Crunch Frappuccino",
    category: "frappuccino",
    defaultMilk: "Whole",
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["dark caramel","frap base","frap roast"],
  },
  {
    name: "Chai Latte",
    category: "tea",
    defaultMilk: "2%",
    defaultIced: false,
    hasHot: true,
    hasIced: true,
    recipeIngredients: ["chai syrup","classic syrup"],
  },
  {
    name: "Cortado",
    category: "espresso",
    defaultMilk: "Whole",
    defaultIced: false,
    hasHot: true,
    hasIced: false,
    recipeIngredients: ["ristretto"],
  },
  {
    name: "Example Drink",
    category: "espresso",
    defaultMilk: "2%",
    defaultIced: false,
    hasHot: true,
    hasIced: true,
    recipeIngredients: ["espresso","mocha sauce"],
  },
  {
    name: "Flat White",
    category: "espresso",
    defaultMilk: "Whole",
    defaultIced: false,
    hasHot: true,
    hasIced: false,
    recipeIngredients: ["ristretto"],
  },
  {
    name: "Honey Citrus Mint Tea",
    category: "tea",
    defaultMilk: null,
    defaultIced: false,
    hasHot: true,
    hasIced: false,
    recipeIngredients: ["honey blend","mint majesty tea bag"],
  },
  {
    name: "Iced Shaken Espresso",
    category: "espresso",
    defaultMilk: "2%",
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["classic syrup","espresso"],
  },
  {
    name: "Latte",
    category: "espresso",
    defaultMilk: "2%",
    defaultIced: false,
    hasHot: true,
    hasIced: true,
    recipeIngredients: ["espresso"],
  },
  {
    name: "Mango Dragonfruit Energy Refresher",
    category: "refresher",
    defaultMilk: null,
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["dragonfruit inclusions","green tea extract"],
  },
  {
    name: "Mango Dragonfruit Refresher",
    category: "refresher",
    defaultMilk: null,
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["dragonfruit inclusions","green tea extract"],
  },
  {
    name: "Mango Strawberry Energy Refresher",
    category: "refresher",
    defaultMilk: null,
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["green tea extract","mango syrup","strawberry inclusions"],
  },
  {
    name: "Mango Strawberry Refresher",
    category: "refresher",
    defaultMilk: null,
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["green tea extract","mango syrup","strawberry inclusions"],
  },
  {
    name: "Matcha Latte",
    category: "tea",
    defaultMilk: "2%",
    defaultIced: false,
    hasHot: true,
    hasIced: true,
    recipeIngredients: ["matcha powder"],
  },
  {
    name: "Mocha",
    category: "espresso",
    defaultMilk: "2%",
    defaultIced: false,
    hasHot: true,
    hasIced: true,
    recipeIngredients: ["espresso","mocha sauce"],
  },
  {
    name: "Mocha Cookie Crunch Frappuccino",
    category: "frappuccino",
    defaultMilk: "Whole",
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["choco chips","frap base","frap roast"],
  },
  {
    name: "Strawberry Acai Energy Refresher",
    category: "refresher",
    defaultMilk: null,
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["green tea extract","strawberry inclusions"],
  },
  {
    name: "Strawberry Acai Refresher",
    category: "refresher",
    defaultMilk: null,
    defaultIced: true,
    hasHot: false,
    hasIced: true,
    recipeIngredients: ["green tea extract","strawberry inclusions"],
  },
] as const;
